version: 0.0
os: windows
files:
  - source: \apppublish
    destination: c:\inetpub\wwwroot\bike
  - source: \delete.ps1
    destination: c:\temp
  - source: \install.ps1
    destination: c:\temp
  - source: \delete.bat
    destination: c:\temp
  - source: \install.bat
    destination: c:\temp
hooks:
  BeforeInstall:
    - location: \delete.bat
      timeout: 180
  AfterInstall:
    - location: \install.bat
      timeout: 180